### ISSUE TITLE
Logo Suggestions?

### ISSUE THREAD

**Issue by B1GBOOM420** [CybrZone/phishkiller#22]
Here is a logo I whipped up for the project - not amazing, but it will work 

you are welcome to use it if you would like
![Untitled](https://github.com/CybrZone/phishkiller/assets/68705432/a497cb20-1e28-4725-b02d-3f04984eac14)

**Comment by asheshjyotii** [comment]
Since you suggested for a logo 
I think it is necessary to take your **opinion** on this.

I'm trying to build this as a cli tool, you can read issue #24

I have tried hard to convert your logo to ASCII and not achieved much perfection 

![Screenshot_2024-07-03-00-58-02-717_ru.iiec.pydroid3.jpg](https://github.com/CybrZone/phishkiller/assets/121642065/b3184dc1-d5a3-4905-9021-eb648dc61150)

![Screenshot_2024-07-03-00-58-07-403_ru.iiec.pydroid3.jpg](https://github.com/CybrZone/phishkiller/assets/121642065/0c004f49-618a-4b47-ab56-cfdf2a003f0e)




Please comment on this:

Is it useless? -> I might request you to suggest another logo

It's good but can be better -> I will make more versions and post here for your review!

@B1GBOOM420

**Comment by B1GBOOM420** [comment]
https://github.com/CybrZone/phishkiller/issues/26#issuecomment-2209497670

@CybrZone 
The "issue" has been addressed and is being worked on in #26
